// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type WebsiteRedirect struct {
	ID          int64
	Originalurl string
	Redirecturl string
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}
